production:
  access_key_id: ACCESS_KEY_ID
  secret_access_key: SECRET_ACCESS_KEY
  bucket: BUCKET
development:
  access_key_id: ACCESS_KEY_ID
  secret_access_key: SECRET_ACCESS_KEY
  bucket: BUCKET
test:
  access_key_id: ACCESS_KEY_ID
  secret_access_key: AMAZON_AWS_SECRET
  bucket: BUCKET
